name: CI
run-name: ${{ github.actor}} runs CI

on: [push]

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        env:
          COMPOSER_ROOT_VERSION: dev-master
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          configuration: phpstan.neon
      - name: PHPunit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9
          configuration: phpunit.xml
